### ISSUE TITLE
pitivi as a snap

### ISSUE THREAD

**Issue by pixelr0** [snapcrafters/fork-and-rename-me#2]
for now the only way to install a newer version of pitivi is a flatpack, pitivi as a snap would be nice

https://pitivi.wordpress.com/2017/09/22/pitivi-0-99-ocean-big-chair/

**Comment by Ads20000** [comment]
You would be better off making the suggestion [here](https://forum.snapcraft.io/t/snap-wishlist-suggestions-wanted/567).

Could an Owner please close this issue? :)

**Comment by Ads20000** [comment]
Also, you can try and fork this repo and make the snap yourself. I haven't actually succeeded in snapping anything yet...but you should start with [this tutorial](https://tutorials.ubuntu.com/tutorial/create-your-first-snap).
