### ISSUE TITLE
Install the FreeEncoderPack?

### ISSUE THREAD

**Issue by awsms** [snapcrafters/fork-and-rename-me#21]
Is there any way to install the encoding pack (http://www.foobar2000.org/encoderpack) so I can convert some music to MP3?

**Comment by lucyllewy** [comment]
You're in the wrong place. This is not a support venue. This repository is merely a template for people to copy.

**Comment by awsms** [comment]
> You're in the wrong place. This is not a support venue. This repository is merely a template for people to copy.

shit didn't saw, thanks man
