### ISSUE TITLE
Help with electron packager

### ISSUE THREAD

**Issue by mahnunchik** [snapcrafters/fork-and-rename-me#27]
Hi @snapcrafters team!

Could you please help to make electron application maker to work better with `sandbox` attribute?

It would be awesome to have simple and working solution to easily pack electron applications.

Related issue and projects:

* Snapcraft builds are always auto rejected https://github.com/electron-userland/electron-installer-snap/issues/74
* PR https://github.com/electron-userland/electron-installer-snap/pull/75
* [Electron Installer: Snap](https://github.com/electron-userland/electron-installer-snap)
* [Electron Forge](https://github.com/electron-userland/electron-forge/)

**Comment by ajhalili2006** [comment]
Hey, @mahnunchik! I would like to recommend to move this issue to the [Snapcraft Forum](https://forum.snapcraft.io) with the `snapcraft` tag when creating an new post so others can see it.
