### ISSUE TITLE
Also, I have a new Android folder on ~/ that I think wasn't previously there.

### ISSUE THREAD

**Issue by Hellgang23666** [snapcrafters/fork-and-rename-me#30]
Also, I have a new Android folder on ~/ that I think wasn't previously there.

I'm using Android Studio 4.1
Build #AI-201.8743.12.41.6858069, built on September 23, 2020
Runtime version: 1.8.0_242-release-1644-b3-6222593 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.4.0-48-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1998M
Cores: 6
Registry: ide.new.welcome.screen.force=true
Non-Bundled Plugins: Dart, io.flutter
Current Desktop: ubuntu:GNOME

_Originally posted by @lapisdecor in https://github.com/snapcrafters/android-studio/issues/78#issuecomment-708056289_

**Comment by merlijn-sebrechts** [comment]
This doesn't seem to be related to this template. According to the original issue thread it doesn't actually seem to be related to snaps at all.
