### ISSUE TITLE
Crash on startup version g4.6.0-m snap release 58

### ISSUE THREAD

**Issue by Luchostein** [snapcrafters/fork-and-rename-me#31]
`~/snap/gzdoom/common/.config/gzdoom$ gzdoom `
GZDoom g4.6.0-m - 2021-05-22 16:34:22 +0200 - SDL version
Compiled on Jul  6 2021

OS: Ubuntu Core 20, Linux 5.4.0-77-generic on x86_64
M_LoadDefaults: Load system defaults.

*** Fatal Error ***
Address not mapped to object (signal 11)
Address: 0x7fffffff8

Generating gzdoom-crash.log and killing process 13546, please wait... sh: 1: gdb: not found
Terminado (killed)

`~/snap/gzdoom/common/.config/gzdoom$ cat gzdoom-crash.log `
*** Fatal Error ***
Address not mapped to object (signal 11)
Address: 0x7fffffff8

System: Linux dubitat 5.4.0-77-generic #86-Ubuntu SMP Thu Jun 17 02:35:03 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

GZDoom version g4.6.0-m (c320db66f4b31256d5ad400610a2e1fab028dfe7)
Command line: /snap/gzdoom/58/bin/gzdoom

Not in a level.

Executing: gdb --quiet --batch --command=gdb-respfile-VqEaOQ

$ ls -l /snap/gzdoom/
total 0
drwxr-xr-x 9 root root 120 jul  5 11:33 57/
drwxr-xr-x 9 root root 120 jul  6 11:02 58/
lrwxrwxrwx 1 root root   2 jul  6 23:01 current -> 58/

**Comment by lucyllewy** [comment]
This isn't the right place to report issues with the gzdoom snap. See `snap info gzdoom` for details:

```
  _Please see the github repo for this snap for more info and bug reporting:_
  https://github.com/Hvassaa/gzdoom-snap
```
